version: "3.7"

networks:
  default:
      name: app-tier
services:
  spark-master:
    image: my/spark
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
       - ./conf/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
       - ./result-dir:/opt/spark/work-dir:rw
    environment:
      - SPARK_WORKLOAD=master
  spark-worker-a:
    image: my/spark
    ports:
      - "9091:8081"    
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKLOAD=worker
    volumes:
       - ./conf/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
       - ./result-dir:/opt/spark/work-dir:rw
  spark-worker-b:
    image: my/spark
    ports:
      - "9092:8081" 
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKLOAD=worker
    volumes:
        - ./conf/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
        - ./result-dir:/opt/spark/work-dir:rw

